"api_key": ""
"boost_webhook": "https://canary.discord.com/api/webhooks/1305150209386479718/Y6vd365opj9JTRl8j0xQuhoQ408ZLGtINid7u6YL8Q9LPdAvgcWzeTd__ZgxUIyl6ex_"
"bot_activity": "Playing Boostility"
"bot_token": "MTMwNTE1MzU0MTg3ODU4MzM4Nw.G-lW3I.FArqkkNeSCPVd_RXye0l_VmiDU9HvNRl1jxh3k"
"debug": true
"nickname": ".gg/boostility"
"custom_bio": "https://discord.gg/boostility | Cheapest boosts only 0.8€ | Join today!"
"change_avatar": true
"change_bio": true
"change_nick": true
"changer_banner": true
"onliner": true
"field_name_invite": "Invite Link"
"owners":
- 1291681627759443968
- 1022541540918296618
- 1296859189112471693
"shop_name": "Boostility"
